### ISSUE TITLE
How to install on WSL

### ISSUE THREAD

**Issue by matsuzaka-ryo** [sqldef/sqldef#407] opened 2023-05-23 05:23 UTC
## Platform

* OS: Linux(WSL)

## Question
@k0kubun 
Hi, I have a question about the installation of `sqldef`.  
I have installed the tar file and inflate it. Then I ran `sudo install ./mssqldef /usr/bin/`.  

I understand that `mysqldef --help` does not work but `mssqldef` also does not work.  
```
$ mssqldef
2023/05/23 14:17:27 Failed to read '[-]': stdin is not piped
```

Could you tell me how to install it on Linux?

**Comment by k0kubun** [comment] 2023-05-25 06:36
It looks like a problem introduced by a past version, which should be fixed later. But it does seem to be installed correctly. Can you try specifying a database name after `mssqldef`?

**Comment by k0kubun** [comment] 2023-11-21 06:09
I believe it's not a bug but a misunderstanding in the interface, so closing it until further information is provided. Thanks.

**Closed by k0kubun** 2023-11-21 06:09 UTC
Labels: mssqldef
